### ISSUE TITLE
CLI does not run if no gluebert.config.json-file exists

### ISSUE THREAD

**Issue by wildhaber** [wildhaber/gluebert-cli#1]
Error:

```
module.js:491
    throw err;
    ^

Error: Cannot find module '/Users/any.user/Projects/gluebert-getting-started/gluebert.config.json'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at CommandInterpreter.getConfiguration (/Users/any.user/.nvm/versions/node/v8.4.0/lib/node_modules/gluebert-cli/cli/interpreter.js:31:16)
    at new CommandInterpreter (/Users/any.user/.nvm/versions/node/v8.4.0/lib/node_modules/gluebert-cli/cli/interpreter.js:13:35)
    at Object.<anonymous> (/Users/any.user/.nvm/versions/node/v8.4.0/lib/node_modules/gluebert-cli/cli/gluebert.js:11:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
```

**Comment by wildhaber** [comment]
solved in @0.0.2
